# Use official Node.js Docker image
FROM node:9.9.0

# Clone the code from the git repo
RUN git clone https://github.com/kkenan/basic-microservices.git

# Set it as working directory
WORKDIR /basic-microservices/node-app

# Install dependencies
RUN npm install

# Expose port
EXPOSE 8081

# Command to run the application
CMD ["node", "index.js"]
